language: python
dist: xenial
python: '3.7'

sudo: required
services:
  - docker

addons:
  chrome: stable
  apt:
    packages:
      - libpq-dev

before_script:
  - LATEST_CHROMEDRIVER_VERSION=`curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE"`
  - curl "https://chromedriver.storage.googleapis.com/${LATEST_CHROMEDRIVER_VERSION}/chromedriver_linux64.zip" -O
  - unzip chromedriver_linux64.zip -d ~/bin

branches:
  only:
    - master
    - development

install:
  - pipenv install

script:
  - python manage.py test
  - python manage.py collectstatic --noinput
  - python manage.py behave

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "development" ]; then
      export PROJECT=myrecommendations;
      docker build -f Dockerfile -t registry.heroku.com/$PROJECT/web .;
      echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com;
      docker push registry.heroku.com/$PROJECT/web;
      wget -qO- https://toolbelt.heroku.com/install.sh | sh;
      heroku container:release web --app $PROJECT;
    fi